# targetNamespace is where the aws-registry secret will be created and maintained
targetNamespace: default
# the aws-registry secret will be added to following serviceAccount
serviceAccountName: default
# Name of the aws registry secret
secretName: aws-registry

# aws.account is the aws account number of the ECR (string)
# aws.region is the aws region where the ECR exists
# aws.accessKeyId is the credential of a read-only user for the ECR
# aws.secretAccessKey is the credential of a read-only user for the ECR
aws:
  account: "abc"
  region: "abc"
  accessKeyId: "abc"        # base64
  secretAccessKey: "abc"    # base64

jobImage: architectminds/aws-kubectl
jobImageTag: 1.1
